[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

### 下部ステータスラインに色がつきます。
[[plugins]]
repo = 'itchyny/lightline.vim'

### 文末の空白を赤く表示します。
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

### インデントが縞模様で見やすくなります。
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
let g:indent_guides_enable_on_vim_startup=1
" ガイドをスタートするインデントの量
let g:indent_guides_start_level=2
" 自動カラー無効
let g:indent_guides_auto_colors=0
" 奇数番目のインデントの色
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#444433 ctermbg=black
" 偶数番目のインデントの色
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#333344 ctermbg=darkgray
" ガイドの幅
let g:indent_guides_guide_size = 1
'''

### Vim から Git を便利に触れるようになります。 lightline が少しリッチになります。
[[plugins]]
repo = 'tpope/vim-fugitive'

### キーバインドを便利にまとめる Submode が使えるようになります。
### 'binding.vimrc' 内の "submode#" を含むバインディングに影響します。
[[plugins]]
repo = 'kana/vim-submode'

# [[plugins]]
# repo = 'tomtom/tcomment_vim'
# on_map = ['<C-/><C-/>']
# 
