[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'
on_i = 1

[[plugins]]
repo = 'tomtom/tcomment_vim'
on_map = ['<C-_><C-_>']

[[plugins]]
repo = 'scrooloose/nerdtree'
on_map = ['Ctrl-E']

